src/bitcoinrpc.cpp
src/bitcoinrpc.h
src/keystore.cpp
src/keystore.h
src/net.cpp
src/net.h
src/qt/overviewpage.cpp
src/qt/overviewpage.h
src/qt/transactionrecord.cpp
src/qt/walletmodel.cpp
src/qt/walletmodel.h
src/rpcdump.cpp
src/rpcnet.cpp
src/util.h
src/wallet.cpp
src/wallet.h
src/walletdb.h

Перенёс 3 RPC команды из Bitcoin Core в Novacoin. 
1) addnode
2) getaddednodeinfo
3) removeaddress
addnode:
https://github.com/bitcoin/bitcoin/commit/72a348fd9a7015aa039f9cbdc9166f388f4725e0
https://github.com/bitcoin/bitcoin/commit/b641c9cd217f7789726bb25ab87cd35e2e5fcaad
https://github.com/bitcoin/bitcoin/commit/f2bd6c28e6bddd75d56d580c28f45d2a8be065ab
https://github.com/bitcoin/bitcoin/commit/f339e9e3391465de4921aea3194f3021016f07d1
https://github.com/bitcoin/bitcoin/commit/74088e862e29821562652986c6bd7c14c3783327
getaddednodeinfo:
https://github.com/bitcoin/bitcoin/commit/67a11bd6c5c28edc5f24574595380c1ddf8becf4
removeaddress:
https://github.com/paveljanik/bitcoin/commit/efc79d1bd19163dd0bdf0940a6528096c78f787a
https://github.com/bitcoin/bitcoin/commit/939ed97373fdea0e8ecb173f1c22eb53b …

RPC: addnode, getaddednodeinfo, removeaddress

---

src/init.cpp
src/qt/transactionview.cpp

1)у меня это устранило https://github.com/novacoin-project/novacoin/issues/96 и https://github.com/novacoin-project/novacoin/issues/95
2)немного увеличить столбец количество, было ![amount](http://i61.tinypic.com/5of80p.jpg)

первоначальное значение для strWalletFileName

---

src/qt/bitcoinunits.cpp
src/qt/bitcoinunits.h
src/qt/coincontroldialog.cpp

показывать 3-й ноль для комиссии в выборе входов

---

src/qt/forms/coincontroldialog.ui

Починил https://github.com/novacoin-project/novacoin/issues/92
Стало:

устранил баг: не работает упорядочивание по приоритетам в "выборе входов"

---

novacoin-qt.pro

Reverts novacoin-project/novacoin#100

Revert "fix MinGW build"

---

doc/building novacoind and novacoinqt under Windows with MinGW.txt

для подробностей смотрите коментарии в https://github.com/novacoin-project/novacoin/pull/100

fix Windows MinGW build

---

src/main.cpp
src/main.h

https://github.com/bitcoin/bitcoin/commit/c4892eb4b3fd7f263f3d8584029a24340837fa66

Log reason for non-standard transaction rejection

---

src/qt/locale/bitcoin_ru.ts
src/qt/multisigdialog.cpp

https://github.com/novacoin-project/novacoin/issues/107
Проверил, работает предупреждение.
Теперь осталось с https://github.com/novacoin-project/novacoin/issues/110 разобраться.(И для RPC, и для GUI)

RedeemScriptSizeWarn

---

src/key.cpp

Как в https://github.com/bitcoin/bitcoin/pull/5634

OpenSSL fix

---

src/key.cpp

как в https://github.com/bitcoin/bitcoin/commit/8d0fd4646099132f0a68d6c3d0da3a6a10ab9631
https://github.com/bitcoin/bitcoin/pull/5640

Improve robustness of DER recoding code

---

src/qt/multisigdialog.cpp

для решения https://github.com/novacoin-project/novacoin/issues/110
Несколько тестов:
Если у вас есть более лучшие варианты текстов ошибок, то напишите сюда. Я изменю и добавлю русский перевод в этот pull request.

предупреждения при создании адреса с мультиподписью

---

src/qt/coincontroldialog.cpp

**CryptoManiac:** 
>Метод удален, а ссылка на него в 108 строке осталась.
исправил

исправлен connect с несуществующим методом

---

src/rpcrawtransaction.cpp
src/rpcwallet.cpp

должно окончательно решить https://github.com/novacoin-project/novacoin/issues/110

предупреждение о максимальном количестве адресов в RPC командах createmultisig и addmultisigaddress

---

src/qt/bitcoingui.cpp
src/qt/locale/bitcoin_ru.ts

ToolTip не показываются для меню. Изменил их на StatusTip

показывать подсказки в меню

---

src/qt/transactionview.cpp

решило эту проблему: https://github.com/novacoin-project/novacoin/issues/130

вернул сортировку по любому полю в "транзакциях"

---

src/qt/coincontroldialog.cpp

Решило https://github.com/novacoin-project/novacoin/issues/135
Но если кто-то знает почему вообще имя менялось с пустого на 1, то лучше исправить причину, чем такой костыль...

явно указываем в .cpp коде имя первого столбца

---

src/base58.h
src/bignum.h
src/init.cpp
src/kernelrecord.cpp
src/main.cpp
src/main.h
src/qt/clientmodel.cpp
src/qt/multisigdialog.cpp
src/qt/walletmodel.cpp
src/script.cpp
src/serialize.h
src/wallet.h

4267: https://msdn.microsoft.com/ru-ru/library/6kck0s93.aspx
4244: https://msdn.microsoft.com/ru-ru/library/th7a07tz.aspx
4800: https://msdn.microsoft.com/ru-ru/library/b6801kcy.aspx
Надеюсь этими исправлениями я ничего не сломал в других компиляторах, но вроде это просто явные приведения типов( и != 0 для приведения к типу bool)
Зато после этих исправлений показывается не ~360 предупреждений, а 27.

устранил некоторые предупреждения компилятора

---

src/init.cpp
src/qt/guiutil.cpp

Меняем шрифт на шрифт, в котором все буквы имеют одинаковую ширину.

выравнивание текста в окне "Параметры командной строки"

---

src/qt/forms/aboutdialog.ui
src/qt/forms/optionsdialog.ui

AboutDialog.ui:
**sir.miklosh:**
>идеально смотрится при
*<*width*>*640*<*/width*>*
*<*height*>*416*<*/height*>*
(на всякий случай подобрал цифры кратные 16)
кстати, по клику на стопку монет можно придумать какую-нибудь пасхалку)
OptiondsDialog.ui:
В русском переводе не влезала фраза: "IP tor прокси"

Размеры форм

---

src/qt/walletmodel.cpp

This reverts commit 6c5d74dedc8804f773e9ec689722cef3c571b034.
Не отображаются новые транзакции с этим коммитом. Мой косяк :(

Revert "производительность Qt"

---

src/rpcdump.cpp

Так же немного изменено поведение команды importprivkey, чтобы стало как у текущего bitcoin
1) Не выдавать ошибку если адрес уже есть
2) Выставлять время создание импортированного адреса 1.

добавлен параметр rescan в RPC вызов "importprivkey"

---

MSVC/libcommon/libcommon.vcxproj
MSVC/libcommon/libcommon.vcxproj.filters
MSVC/mynovacoin/mynovacoin.vcxproj
MSVC/mynovacoinqt/mynovacoinqt.vcxproj
novacoin-qt.pro
src/init.cpp
src/makefile.bsd
src/makefile.linux-mingw
src/makefile.mingw
src/makefile.osx
src/makefile.unix
src/scrypt-sse2.cpp
src/scrypt.cpp
src/scrypt.h

scrypt SSE2

---

novacoin-qt.pro
src/qt/bitcoin.cpp
src/qt/forms/intro.ui
src/qt/guiutil.cpp
src/qt/intro.cpp
src/qt/intro.h

Появляется при первом запуске или если запустить так:
novacoin-qt.exe -choosedatadir
После включения этого коммита нужно будет запустить 
lupdate novacoin-qt.pro 
и обновленный bitcoin_en.ts добавить на transifex

выбор папки для базы блоков из GUI

---

src/scrypt-sse2.cpp

fix issue https://github.com/novacoin-project/novacoin/issues/192

fix issue 192

---

src/keystore.h
src/script.h

C4701 - script.h
C4702 - keystore.h

Remove msvc warnings.

---

src/allocators.h
src/base58.h
src/netbase.cpp
src/util.cpp

https://github.com/bitcoin/bitcoin/commit/0f8a6477825fbaad0d37233bdd3011d748f607ab#diff-4942713bcd2752bb531bf76c9a0ba38e

Перенос данного коммита:

---

src/netbase.cpp

Correct some proxy related socket leaks.

Merged from bitcoin 0bd05b5

---

MSVC/mynovacoinqt/mynovacoinqt.vcxproj
MSVC/mynovacoinqt/mynovacoinqt.vcxproj.filters

To Do list:
fix C1083 can't find scrypt.h in libcommon solution
fix MSB8017 circular dependency then building overviewpage.moc, rpcconsole.moc and intro.moc

Novacoin-qt solution - added form "intro".

---

src/db.cpp
src/main.cpp
src/qt/addressbookpage.cpp
src/rpcmining.cpp
src/rpcrawtransaction.cpp
src/txdb-bdb.cpp

Просьба проигнорировать aef6882 , попал повторно.

Fix QRCode contextMenu

---

src/qt/forms/coincontroldialog.ui
src/qt/forms/multisigdialog.ui
src/qt/forms/sendcoinsdialog.ui

Учитывая также то, что добавилась форма intro, можно протолкнуть обновлённый перевод на transifex

Do not translate the untranslatable

---

src/util.cpp

Оставлю этот коммит как заметку. В коде есть масса подобных ситуаций , msvc высказывается так https://msdn.microsoft.com/en-us/library/6kck0s93%28v=vs.140%29.aspx

Fix msvc c4267 warning

---

src/ntp.cpp
src/ntp.h

- const declarations
- type mismatch
- msvc c4706 assignment within conditional expression

Various ntp files fixes:

---

src/init.cpp
src/rpcblockchain.cpp
src/rpcrawtransaction.cpp
src/rpcwallet.cpp
src/util.h
src/wallet.cpp

-usless cast (ptime)
-hashBlock pass by reference
-%u for unsigned int
-fRet: simplified assignment

Small code fixes:

---

src/main.cpp

flying delorean transaction exploit fix (zero cost mempool memory exhaustion exploit)
https://github.com/ppcoin/ppcoin/pull/104

zero cost mempool memory exhaustion exploit

---

contrib/docker_builder/README.md
contrib/docker_builder/dockerfile

Add dockerfile for building nvc client

---

src/netbase.cpp

replace 3 separate calls to WSAGetLastError() with 1

---

src/main.cpp
src/net.h

net.h via main.h
protocol.h via addrman.h

Reorganize includes a bit.

---

src/compat.h
src/irc.cpp
src/net.cpp
src/net.h
src/netbase.cpp
src/netbase.h
src/ntp.cpp
src/stun.cpp

Also small code rewrite (stun.cpp) based on https://msdn.microsoft.com/en-us/library/windows/desktop/ms740506%28v=vs.85%29.aspx

Add CloseSocket (bitcoin@43f510d37d680ca4347878d2fb6f8b97b54e7611)

---

MSVC/libcommon/libcommon.vcxproj

Line #23 is repeated in #55, leading to problems with the compilation.

Remove extra line

---

src/wallet.cpp

See https://github.com/bitcoin/bitcoin/pull/1872/

Fix listaddressgroupings comand

---

src/checkqueue.h
src/crypto/scrypt/generic/scrypt-generic.cpp

quick fix for https://github.com/novacoin-project/novacoin/commit/df22c96b92f6fd786d7a08ea8333f22cd943c644
fix for -DUSE_ASM=0 branch

Minor fix for c++11 branch

---

src/qt/rpcconsole.cpp

https://github.com/bitcoin/bitcoin/pull/1767

Clear history when using clear button in RPC console
