- src/qt/optionsmodel.cpp
- src/rpcrawtransaction.cpp
1) Показывать scryptPubKey в hex и asm формате в выводе RPC команды decoderawtransaction
Устранит такие неудобства: https://bitcointalk.org/index.php?topic=704756.msg9978930#msg9978930
2) Добавление четвёртого blockexplorer'а  в контекстное меню транзакций. Чтобы заработало, нужно удалить параметр strThirdPartyTxUrls в реестре Windows, который находится по пути: HKEY_CURRENT_USER\Software\NovaCoin\NovaCoin-Qt
> показывать scryptPubKey в hex и asm формате

- novacoin-qt.pro
Спасибо пользователю **Victor1739**, который заметил что MinGW сборки не работают.
Произошло неудачное стечение обстоятельств.
https://github.com/novacoin-project/novacoin/pull/86
1) **0xDEADFACE** добавил коммит https://github.com/novacoin-project/novacoin/commit/f67b5c1eb1c6e1660be48f1c93013219f17486a5
2) Примерно в это же время я синхронизировал fsb4000/novacoin до актуального novacoin-project/novacoin чтобы сделать https://github.com/novacoin-project/novacoin/pull/86 с переводом
3) **0xDEADFACE** откатывает этот коммит, когда видит что он ломает MinGW билд
4) я делаю https://github.com/novacoin-project/novacoin/pull/86
5) и этот коммит остаётся в моём пул реквесте
6) **CryptoManiaс** merged пул реквест, и коммит снова возвращается в novacoin-project
Хорошо что заметили до релиза 0.5.1 …
> fix MinGW build

- src/qt/bitcoingui.cpp
- src/qt/clientmodel.cpp
- src/qt/clientmodel.h
- src/qt/forms/rpcconsole.ui
- src/qt/locale/bitcoin_ru.ts
- src/qt/rpcconsole.cpp
- src/qt/rpcconsole.h
Перенёс несколько коммитов из Bitcoin связанных с RPC console
1)https://github.com/bitcoin/bitcoin/commit/4a8fc152a957e54e6dd910de4382678f5c405198
RPC console становится Widget вместо Dialog. То есть теперь окошко RPC консоли не будет сворачиваться, если нажать свернуть у кошелька. С другой стороны RPC консоль теперь не всегда поверх кошелька, то есть может скрываться за кошельком. Иногда это неудобно...
2)https://github.com/bitcoin/bitcoin/commit/fe6bff2eaec35c3dc292af883a6e82397e440c22 
Показывать версию BerkeleyDB в RPC консоли
3)https://github.com/bitcoin/bitcoin/pull/4300
Не сохранять повторные команды в истории RPC консоли
4)https://github.com/bitcoin/bitcoin/pull/3685
Показывать не просто число подключений кошелька, а число входящих/исходящих подключений.
Вот так примерно стала …
> Rpc console

- src/net.cpp
**lservAddressesToAdd.erase(it)** возвращает итератор, который указывает на первый элемент, оставшиеся за всеми удаленными элементами, или указывает на конец списка, если такой элемент не существует.  Если список пуст, то **lservAddressesToAdd::end** == **lservAddressesToAdd::begin**. Если **it == lservAddressesToAdd::begin**, то **it--;** вызовет ошибку времени исполнения: "List iterator not dereferencable" 
Если **it == lservAddressesToAdd::end**, то **it++**(в цикле for) вызовет ошибку времени исполнения:"List iterator not incrementable"
Такое поведение у Microsoft Visual C++ в 2012 студии. У gcc скорее всего было всё нормально, раз баг не был замечен ранее...
> fix "List iterator not dereferencable" and "List iterator not incrementable"

- src/qt/mintingtablemodel.cpp
(Qt::EditRole выбран для сортировки в файле mintingview.cpp , в функции void MintingView::setModel(WalletModel *model) , в строке mintingProxyModel->setSortRole(Qt::EditRole); )
Должно решить эту проблему: https://github.com/novacoin-project/novacoin/issues/91
> использовать актуальное значение "монетодней" для сортировки  во вкладке POS

- COPYING
- doc/building novacoin-qt for android under Windows.txt
- src/compat.h
- src/netbase.cpp
- src/qt/aboutdialog.cpp
- src/qt/aboutdialog.h
- src/qt/bitcoingui.cpp
- src/qt/bitcoingui.h
- src/qt/forms/aboutdialog.ui
- src/qt/locale/bitcoin_ru.ts
- src/util.cpp
1) Изменил *#*inсlude , теперь не нужно дополнительно править при построении Android клиента
2) Изменил базовый класс AboutDialog с QDialog на QWidget. В Windows, Linux, Mac, FreeBSD ничего не должно поменяться, но в Android будет заметно. Окно About будет на весь экран. Гораздо удобнее. Нужно будет так же изменить классы у MultisigDialog и CoinControlDialog
3)Обновил дату авторских прав. Так же добавил разработчиков PPCoin, разработчиков Peerunity, разработчиков EmerCoin в список авторов.
> Android, AboutDialog, Copyright

- src/qt/coincontroldialog.cpp
- src/qt/coincontroldialog.h
- src/qt/coincontroltreewidget.cpp
- src/qt/forms/coincontroldialog.ui
- src/qt/sendcoinsdialog.cpp
- src/qt/sendcoinsdialog.h
1) Был баг: Если в CoinControl кликнуть мышкой в область с деревом входов, но не выбирать ни один вход и нажать "пробел", то будет вылет. 
Исправление падения при нажатии пробела в CC решило это.
(this->currentItem() возвращает текущий элемент в виджете-дереве, если не выбрано элементов, то возвращает NULL)
2) Изменён базовый класс для CoinControl на QWidget
> Coin control

- src/qt/coincontroldialog.cpp
- src/qt/coincontroldialog.h
Увидел здесь: https://github.com/bitcoin/bitcoin/pull/5651
У нас меньше исправлений, потому что у нас комиссия зависит от целового количества килобайт, а не просто от количества байт. И потому что при копировании копируется значение целиком, вместе со знаком. То есть ≈226 и ~226, а не просто число. Но я не думаю что нужно это менять, так как при вставке ,например, в калькулятор, калькулятор нормально воспринимает это как 226.
> использовать UTF8 знак примерно равно

- src/qt/multisigaddressentry.cpp
Описание проблемы:
1)Откройте окно для работы с мультиподписью(файл -> мультиподпись)
2)Выберите адрес с меткой
3)Выберите другой адрес без метки, но в поле "Метка" останется  метка предыдущего адреса.
Этот патч решает описанную выше проблему.
> правильно показывать метку адреса в multisigdialog

- MSVC/build-helpers/buildboost.bat
- MSVC/build-helpers/buildopenssl.bat
- MSVC/libcommon/libcommon.vcxproj
- MSVC/mynovacoin/mynovacoin.vcxproj
- MSVC/mynovacoinqt/mynovacoinqt.vcxproj
- doc/building novacoind and novacoinqt under Windows with MSVC.txt
1)Обновил OpenSSL до 1.0.2
2)Обновил Boost до 1.57
3)Убрал определение препроцессора: *_*WINSOCKAPI*_*  .  Оно стало не нужно после этого коммита: https://github.com/novacoin-project/novacoin/commit/5fddc4755daf043e8e927fd97bf2c80ad9d819e5
4)Немного изменил флаги оптимизации программы.
> обновление библиотек для MSVC сборки

- src/qt/forms/rpcconsole.ui
- src/qt/guiutil.cpp
- src/qt/guiutil.h
- src/qt/locale/bitcoin_ru.ts
- src/qt/rpcconsole.cpp
- src/qt/rpcconsole.h
- src/util.cpp
Реализовано улучшение: https://github.com/novacoin-project/novacoin/issues/143
Выглядит так:
Похоже на https://github.com/jl777/btcd/commit/be2f7323faba13d7ad729c1f988ee2effd235401
> Автоматическое создание novacoin.conf + кнопка для открытия novacoin.conf в Qt версии кошелька

- src/crypter.h
Решает проблему https://github.com/novacoin-project/novacoin/issues/146
Чтобы точнее понять, посмотрите функцию bool CCrypter::SetKeyFromPassphrase в файле /src/crypter.cpp
> sha512 шифрование имеет индекс 0, а не 1

- src/qt/transactiondescdialog.cpp
- src/qt/transactiondescdialog.h
- src/qt/transactionview.cpp
Я ошибся, нет встроенного сигнала close() у QWidget :)
> использование правильного сигнала закрытия окна

- src/qt/sendcoinsentry.cpp
Описание бага:
1)Откройте novacoin-qt
2)Перейдите во вкладку "Отправка монет"
3)Нажмите "Выберите из адресной книги" напротив получателя
4)Выберите адрес с меткой
5)Опять нажмите "Выберите из адресной книги" напротив этого же получателя
6)Выберите адрес без метки
7)Метка предыдущего адреса останется для адреса без метки.
> починка бага: метка предыдущего адреса сохранялась для адреса без метки

- src/qt/locale/bitcoin_en.ts
- src/qt/locale/bitcoin_ru.ts
Теперь при вызове qmake (Qt5) не будет выдаваться:
warning : ignoring *<*defaultcodec*>* element
Совместимость с Qt 4.8.6 не пострадала от удаления *<*defaultcodec*>*UTF-8*<*/defaultcodec*>*.
> устранил "warning : ignoring <defaultcodec> element"

- src/qt/guiutil.cpp
- src/qt/guiutil.h
Чем сохранять файлы в кодировке UTF-8 в Windows? По умолчанию сохраняет как ANSI, поэтому русские коментарии не отображаются. Если сохранять "блокнотом" как UTF-8, то меняет первую строчку(добавляет первым символом(В ANSI кодировки) я╗┐(невидимый когда открывается в UTF-8 кодировке)). А чем сохранять, чтобы текст сохранялся в UTF-8 и не менялась первая строчка?
Пока использую такое решение:
1)Сохраняю блокнотом в UTF-8
2)Открываю файл встроенным в Far Manager редактором  и удаляю первый символ
> Окно параметров командной строки может менять размер и появилась кнопка закрыть("крестик")

- src/allocators.h
- src/init.cpp
- src/qt/bitcoingui.cpp
- src/qt/bitcoingui.h
- src/qt/multisigdialog.cpp
- src/qt/optionsmodel.cpp
- src/txdb-leveldb.h
Так же удалил BitcoinGUI::error, так как весь функционал этой функции уже есть в BitcoinGUI::message, к тому же при вызове BitcoinGUI::error использовались параметры BitcoinGUI::message ( CClientUIInterface::MSG_ERROR имеет тип int, а не bool требуемый BitcoinGUI::error)
Осталось 2 предупреждения, пока не знаю как их исправить:
> устранил некоторые предупреждения компилятора

- src/qt/bitcoingui.cpp
- src/qt/bitcoingui.h
https://github.com/novacoin-project/novacoin/pull/160#issuecomment-74277788
**0xDEADFACE:**
>```
QObject::connect: No such slot BitcoinGUI::error(QString,QString,bool)
QObject::connect: No such slot BitcoinGUI::error(QString,QString,bool)
```
При запуске.
Вернул назад.
> вернул BitcoinGUI::error

- src/qt/bitcoinstrings.cpp
- src/qt/locale/bitcoin_en.ts
- src/qt/locale/bitcoin_ru.ts
Добавил строки для перевода в bitcoinstrings.cpp, которые lupdate не нашёл и пометил пропавшими(type="vanished"). Видимо потому что эти строки мы добавляли вручную(они есть в init.cpp, без добавления в bitcoinstrings.cpp они остаются непереведенными)...
Обновился до текущего мастера и сделал повторно lupdate.(из-за этого обновились часть номеров строк)
Так же удалил из перевода:
*<*message*>*
*<*source*>*123.456 BTC*<*/source*>*
*<*translation type="vanished"*>*123.456 BTC*<*/translation*>*
*<*/message*>*
В форме у нас 123.456 NVC, вариант с BTC оставался только в файле переводов(причём помеченный как vanished)
Надеюсь больше ничего не забыл.
> Обновил строки для перевода

- src/qt/walletmodel.cpp
не пытаемся обновить нашу вкладку "транзакции", если транзакция
предназначалась не нам. Очень существенно повышает отзывчивость GUI при
синхронизации.
> производительность Qt

- src/qt/forms/overviewpage.ui
- src/qt/locale/bitcoin_en.ts
- src/qt/overviewpage.cpp
Иногда полезно увидеть общее количество монет: те что доступны + те что созревают после  PoS блока + те что созревают после PoW  блока.
Так же Unspendable: перенёс вниз, так как эта строка всё равно почти всегда не видна, зато теперь нет непонятной пустой строки между "Баланс" и "Доля"
Не переводил, так как теперь весь перевод тут: https://www.transifex.com/projects/p/novacoin/
Особо не тестировал...
> показывать на главной странице общее число монет кошелька

- src/util.cpp
@CryptoManiac:
>Поломалась совместимость со старым бустом (1.48):
>
```
util.cpp: In function 'void createConf()':
util.cpp:1160: error: 'struct boost::filesystem::path' has no member named 'generic_string'
```
В принципе, несущественно.
> возвращение совместимости со старым boost

- src/qt/forms/overviewpage.ui
Развернул novacoin-qt на полный экран и увидел, что с выравниванием справа реально далеко числа балансов и описания. В оконном режиме выглядело нормально...
> вернул балансам выравнивание слева.

- src/bitcoinrpc.cpp
- src/util.cpp
- src/util.h
Фактически перенос этого коммита https://github.com/laanwj/bitcoin/commit/3e8ac6af9a993e262d1160fb2e6e1e1f1d5d19f2
Как следствие сокращает количество warning-ов при компиляции в msvc. В плане тестов: данная сборка живёт более суток на трёх нодах (ubuntu-arm gcc и win32 msvc сборки), сгенерировано несколько валидных pos блоков в основной сети.
> Replace non-threadsafe gmtime and setlocale

- src/qt/optionsmodel.cpp
@svost
>похоже глюк нашел
настройки опции ставь галку подключаться через тор, от балды прописываешь айпишник, главное не 127 0 0 1, закрываешь прогу, открываешь заново - 127 0 0 1 на месте
> исправлена смена IP для Tor proxy.

- src/qt/forms/overviewpage.ui
- src/qt/overviewpage.cpp
- src/qt/rpcconsole.cpp
Теперь метка "Бумажник"(точнее уже Балансы) и команды в rpc консоли будут иметь корректный размер на Android или на HighDPI десктопах.
> убраны фиксированные размеры шрифтов.

- src/netbase.cpp
> Hurricane Electric uses block 2001:470::, not 2011:470::

- src/version.cpp
Возможно, следует переместить данное дополнение в строку "Дата сборки" с одновременным переименованием т.к. строка версия клиента уже является довольно длинной. К примеру: "Сборка"  mingw , Apr 26 2015, 21:06:05.
> Version: compiler name suffix

- src/qt/bitcoingui.cpp
По просьбам: https://bitcointalk.org/index.php?topic=704756.msg12024413#msg12024413
Правда добавил в всплывающую подсказку о синхронизации, так как и PoW и PoS. Но можно переделать и добавить в всплывающую подсказку о состоянии майнера...
> add PoS and PoW difficulty to tooltip

- src/qt/bitcoingui.cpp
Отвечу для чего это нужно.
Если вызвать окно Debug window и заслонить его основной формой, то при повторном его вызове кликом из меню оно не переходит на передний план. Приходится выбирать табом или кликом из системной панели. Аналогичная ситуация с окном мультиподписи. Эту замену     multisigPage->activateWindow();
//    multisigPage->setFocus();
оставлю как якорь, тк в старом варианте почему то не всегда срабатывал фокус. Мой коммит исправляет неудобство с переводом форм на передний план.
> Add raise() for MultisigPage and for RpcConsole

- src/net.cpp
NodeSyncScore() should find the node which we recv data most recently, so put a negative sign to pnode->nLastRecv is indeed wrong.
Also change the return value type to int64_t.
Signed-off-by: Huang Le <4tarhl@gmail.com>
> Use pnode->nLastRecv as sync score directly

- src/serialize.h
Оставлю этот коммит как заметку. В коде есть масса while ( true ) и while ( 1 ) , msvc любит так
for ( ; ; ) ссылка на  https://msdn.microsoft.com/en-us/library/6t66728h%28v=vs.90%29.aspx
Будем причёсывать к единообразию?
> Fix msvc c4127 warning

- src/init.cpp
- src/netbase.cpp
Just an alias for onlynet=tor, but matches the new name
of the proxy option -onion= better.
bitcoin/bitcoin@60dc8e4208058814494b301c355a5996af9517a9
>  Allow -onlynet=onion to be used

- src/main.cpp
The only time when a client sends a "getaddr" message is when he
esatblishes an Outbound connection (see ProcessMessage() in
src/main.cpp).  Another bitcoin client is expected to receive a
"getaddr" message only on Inbound connection. Ignoring "gettaddr"
requests on Outbound connections can resolve potential privacy issues
(and as was said such request normally do not happen anyway).
Rebased-From: dca799e1db6e319fdd47e0bfdb038eab0efabb85
Github-Pull: #5442
> Ignore getaddr messages on Outbound connections.

- src/init.cpp
- src/net.cpp
WSAStartup should be called before using any other socket
functions. BindListenPort is not called if not listening.
Closes bitcoin issue #2585.
> Move WSAStartup to init

- MSVC/libcommon/libcommon.vcxproj.filters
- src/kernel_worker.cpp
also double inclusion removed in libcommon.vcxproj.filters
> MSVC compatibility with USE_ASM definition

- src/base58.h
- src/bitcoinrpc.h
- src/main.h
- src/net.h
- src/netbase.h
- src/protocol.h
- src/script.h
- src/serialize.h
Transform enum {a,b,}; to enum {a,b};
> Code cleanup (icc warning #271 trailing comma is nonstandard)

- doc/crosscompiling_building Windows binary under Unix.txt
- src/makefile.mingw
@svost заметил что novacoin не собирается по текущей инструкции, так же указал на таргет clean. Я посмотрел и увидел что mxe теперь собирает gcc вместе с pthread и внёс необходимые изменения в инструкцию.
Также немного упростил инструкцию:
-используем mxe libpng, а не скаченный самостоятельно
-используем BOOST_THREAD_LIB_SUFFIX вместо ручного изменения имени библиотеки
-добавляем инструкции к таргету clean для работоспособности в Linux
-удаляем лишние пути /home/<ваше имя>/mxe/usr/i686-w64-mingw32.static/lib и /home/<ваше имя>/mxe/usr/i686-w64-mingw32.static/lib  так как они по умолчанию есть в компиляторе.
> адаптация инструкции к текущей версии mxe

- src/ecies.cpp
- src/key.cpp
- src/rpcrawtransaction.cpp
В общем без этого изменения MSVC падает при сборке key.cpp с аналогичными симптомами http://stackoverflow.com/questions/1372480/c-redefinition-header-files-winsock2-h Текущий рабочий вариант проверен на msvc, mxe и линуксовой сборке.
> Reorganize includes a bit.

- src/init.cpp
- src/kernel.cpp
- src/util.h
Из-за добавления std::chrono и std::thread получили временную мешанину с boost::thread к примеру. Поэтому на данном этапе прописываем развернутый вариант, как пример: std::thread::hardware_concurrency()
> Minor fix: c++11 branch

- src/net.cpp
- src/net.h
- src/stun.cpp
Для 683b6a3 после инициализации = {}; memset не нужен.
http://www.imagebam.com/image/00deb9478422089
> Minor restyle whith std=c++11
